FROM golang:1.10-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /zynecoin
RUN cd /zynecoin && make bootnode

RUN chmod +x /zynecoin/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="etienne@zynecoin.com"

WORKDIR /zynecoin

COPY --from=builder /zynecoin/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
